# Generated by Django 5.1.1 on 2024-09-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_reg',
            name='name',
        ),
        migrations.AddField(
            model_name='user_reg',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
