# Generated by Django 5.1.1 on 2024-09-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_remove_user_reg_name_user_reg_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='username',
            field=models.CharField(default='default_username', max_length=100, unique=True),
        ),
    ]
